packages:
  - packages/*
  - apps/*
  - tests/bundle/*
  - tests/integrations/*
allowBuilds:
  sharp@0.34.5: true
minimumReleaseAgeExclude:
  - '@vitejs/plugin-react@6.0.4'
  - react-dom@19.2.8
  - react@19.2.8
  - '@publint/pack@0.1.6'
  - publint@0.3.22
